### PR TITLE
Add Aurora

### PR DESCRIPTION
**Pull request by amazinigmech2418**
Sorry. I renamed it to AmazingMech2418 -  Aurora after I got fired. You can change it if needed.

### CODE REVIEW

**Comment by amazinigmech2418** [comment]
@CStafford-14

**Comment by CStafford-14** [comment]
It's okay. Thanks so much!

**Comment by amazinigmech2418** [comment]
You're welcome!

**Comment by CStafford-14** [comment]
Alright. If you have any questions, just ask any of us at any time.

**Comment by amazinigmech2418** [comment]
OK. Are you going to change the policy on what's needed to join?

**Comment by CStafford-14** [comment]
Well, I guess I can make an exception. I do need to know, who was it that said you couldn't sign up? Was it you? Parents? The websites themselves?

**Comment by CStafford-14** [comment]
Also, how does Aurora work in here? Did you use saodtheking's engine?

**Comment by amazinigmech2418** [comment]
My parents. Also, who's saodtheking? I made it myself. I'm using a similar method to make a robot that can run on a raspberry pi with Scratch and be able to do anything. It would be like Rosie from the Jetsons. Basically, it uses lists to store all information. I also made all hacked blocks in there.

**Comment by CStafford-14** [comment]
Sadotheking is a Scratcher I found who could make the chat engine for Aurora. All I wanted you to do was to tweak it so it would work.

**Comment by amazinigmech2418** [comment]
OK. @CStafford-14 I just made my own because the original was a very basic version with high limitations.

**Comment by CStafford-14** [comment]
What limitations? It's really easy. All you need to do are to detect keywords and give it an output. It's like Google, where it searches for the given keywords, and sees if there's a valid response to that.

**Comment by APEXCCPlymJoe** [comment]
Your version is only made for conversation @amazinigmech2418

**Pull request merged**
